---
- hosts: localhost
  tasks:
    - name: Create a new user
      user:
        name: second-user
        state: present

    - name: Change the shell for the newly created user
      user:
        name: second-user
        shell: /bin/sh

    - name: Create a new group
      group:
        name: second-group
        state: present

    - name: Add user to the group
      user:
        name: second-user
        groups: second-group
        append: yes
